version: "3"
services:
  db:
    image: postgres:15.0
    restart: always
    ports:
      - 5434:5432
    env_file:
      - .env
    volumes:
      - ./init-multi-postgres-databases.sh:/docker-entrypoint-initdb.d/init-multi-postgres-databases.sh
